# -*- coding: utf-8 -*-


# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 480)
        MainWindow.setMinimumSize(QtCore.QSize(500, 480))
        MainWindow.setMaximumSize(QtCore.QSize(500, 480))
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_enter_grade = QtWidgets.QLabel(self.centralwidget)
        self.label_enter_grade.setGeometry(QtCore.QRect(30, 180, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_enter_grade.setFont(font)
        self.label_enter_grade.setObjectName("label_enter_grade")
        self.label_enter_student_name = QtWidgets.QLabel(self.centralwidget)
        self.label_enter_student_name.setGeometry(QtCore.QRect(30, 70, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_enter_student_name.setFont(font)
        self.label_enter_student_name.setObjectName("label_enter_student_name")
        self.input_line_student_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line_student_name.setGeometry(QtCore.QRect(30, 110, 361, 31))
        self.input_line_student_name.setObjectName("input_line_student_name")
        self.input_line_student_grade = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line_student_grade.setGeometry(QtCore.QRect(30, 220, 361, 31))
        self.input_line_student_grade.setObjectName("input_line_student_grade")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(40, 310, 351, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_output.setFont(font)
        self.label_output.setText("")
        self.label_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_output.setObjectName("label_output")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(30, 20, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(50, 260, 81, 31))
        self.button_submit.setObjectName("button_submit")
        self.button_reset = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset.setGeometry(QtCore.QRect(290, 260, 81, 31))
        self.button_reset.setObjectName("button_reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grade Calculator"))
        self.label_enter_grade.setText(_translate("MainWindow", "Enter the student grade:"))
        self.label_enter_student_name.setText(_translate("MainWindow", "Enter the name of  a student:"))
        self.label_title.setText(_translate("MainWindow", "Grade Calculator"))
        self.button_submit.setText(_translate("MainWindow", "Append"))
        self.button_reset.setText(_translate("MainWindow", "Reset File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
